### ISSUE TITLE
Merging bsb-http-chunked into blaze-builder?

### ISSUE THREAD

**Issue by sjakobi** [blaze-builder/blaze-builder#1]
I extracted the `bsb-http-chunked` package from `blaze-builder` back when `blaze-builder` seemed largely unmaintained and in demise.

`warp` now uses `bsb-http-chunked`, but [`http-streams`](https://github.com/aesiniath/http-streams/issues/108) and [`snap-server`](https://github.com/snapframework/snap-server/pull/109) have stuck with `blaze-builder` so far.

Now that `blaze-builder` is actively maintained again, it seems pretty pointless to maintain the same API in two places. 

The main changes that I expect I could contribute to `Blaze.ByteString.Builder.HTTP` are:

* Docs improvements
* Test improvements
* Benchmark improvements
* Possibly refactorings and very minor performance improvements

I'm not very keen to be involved in general package maintenance, but I'd be willing to help with issues specific to `Blaze.ByteString.Builder.HTTP`.

What do you think?

**Comment by andreasabel** [comment]
I am just a bound-bumper here, really, maybe @jaspervdj has more specific opinions.
I am happy for contributions that maintain backwards-compatibility: these are uncontroversial.  For larger changes, one would have to dig deeper into the material.
@sjakobi, I invited you to the organization, and I would appreciate if you made your membership public (in case you accept).  I think it is good if one can see who is part of the maintainer group of a package.

**Comment by jaspervdj** [comment]
`blaze-builder` was originally written by Simon Meier and me in an attempt to get fast string concatenation for `blaze-html`.  Initially, it lived as a part of `blaze-html` and later as a separate package (since fast string concatenation is useful in many places).

Simon's vision was that this code should really be part of ByteString, and I still think this is the right approach.  However, after the code was ported to ByteString, this package sort of stuck around, mostly due to gaps in the API, like @sjakobi pointed out. Having an additional package `bsb-http-chunked` to fill this gap sounds like the right way forward to me.

**Comment by sjakobi** [comment]
Alright. If the goal still is to eventually retire `blaze-builder`, I'll keep `bsb-http-chunked` as a separate package.

Thanks for the feedback! :)
